# Generated by Django 4.2.7 on 2023-11-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0016_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('Grama', 'Grama'), ('Ml', 'Ml'), ('Quantidade', 'Quantidade')], default=1),
            preserve_default=False,
        ),
    ]
